theme: jekyll-theme-cayman
title: Stock Price Prediction with Regression and LSTM
authors: Felix Le Hong Phuoc
description: This project presents two methods of how to predict a timeseries composed of real values. Specifically, we will predict the stock price of a large company listed on the NYSE stock exchange given its historical performance by using two type of models: regression and LSTM (long short-term memory) 
